# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'rake', '~> 13.1'
gem 'rspec', '~> 3.12'
gem 'rubocop', '~> 1.44.0'
gem 'rubocop-performance', '~> 1.16.0'
gem 'rubocop-rake', '~> 0.6.0'
gem 'rubocop-rspec', '~> 2.15.0'
