# frozen_string_literal: true

require 'rubygems'
require 'bundler'

Bundler::GemHelper.install_tasks

$LOAD_PATH.unshift File.expand_path('lib', __dir__)

Dir['./rake/*.rb'].each do |f|
  require f
end

file 'lib/cucumber/ci_environment/CiEnvironments.json' => '../CiEnvironments.json' do |t|
  FileUtils.cp t.prerequisites[0], t.name
end

task 'spec:warnings' => 'lib/cucumber/ci_environment/CiEnvironments.json'

task default: ['spec:warnings']
