# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('lib', __dir__))

file :ci_environments do
  FileUtils.cp('../CiEnvironments.json', 'lib/cucumber/ci_environment/CiEnvironments.json')
end

desc 'Copy the sample environments & run all the unit tests for all environment types'
task spec: :ci_environments do
  system('bundle exec rspec')
end
task default: [:spec]
