name: Release create-meta

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - main

jobs:

  pre-release-check:
    name: Pre-release checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check commit has been pushed on origin/main
        run: |
          git fetch --quiet origin main
          # git merge-base --is-ancestor HEAD origin/main

  test-ruby:
    uses: cucumber/create-meta/.github/workflows/test-ruby.yml@main

  test-javascript:
    uses: cucumber/create-meta/.github/workflows/test-javascript.yml@main

  test-java:
    uses: cucumber/create-meta/.github/workflows/test-java.yml@main

  publish-rubygem:
    name: Publish Ruby Gem
    needs: [pre-release-check, test-java, test-javascript, test-ruby]
    runs-on: ubuntu-latest
    # environment: Release

    steps:
      - uses: actions/checkout@v2

      # - name: Publish ruby gem
      #   uses: cucumber/action-publish-rubygem@v1.0.0
      #   with:
      #     working_directory: ruby
      #     rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}

  publish-mvn:
    name: Publish Maven Package
    needs: [pre-release-check, test-java, test-javascript, test-ruby]
    runs-on: ubuntu-latest
    # environment: Release

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      # - uses: cucumber/action-publish-mvn@v1.0.0
      #   with:
      #     gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      #     nexus-username: cukebot
      #     nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
      #     working-directory: java

  publish-npm:
    name: Publish NPM module
    needs: [pre-release-check, test-java, test-javascript, test-ruby]
    runs-on: ubuntu-latest
    # environment: Release

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: javascript/package-lock.json

      # - uses: cucumber/action-publish-npm@v1.0.0
      #   with:
      #     npm-token: ${{ secrets.NPM_TOKEN }}
      #     working-directory: javascript

  create-github-release:
    name: Create GitHub Release and Git tag
    needs: [publish-rubygem, publish-mvn, publish-npm]
    runs-on: ubuntu-latest
    # environment: Release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      # - uses: cucumber/action-create-github-release@v1.1.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
