name: test-ruby

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - ruby/**
      - CiEnvironments.json
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - ruby/**
      - CiEnvironments.json
      - testdata/**
      - .github/**

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.2', '3.3', '3.4', '4.0']
        include:
          - os: windows-latest
            ruby: '4.0'
          - os: macos-latest
            ruby: '4.0'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby
      - run: bundle exec rake
        working-directory: ruby
      - run: ./scripts/fail-if-dirty
