---
name: test-javascript

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node-version: [18, 20, 22]
        include:
          - os: windows-latest
            node-version: 22
          - os: macos-latest
            node-version: 22
    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - name: with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: javascript/package-lock.json
      - run: npm install-ci-test
        working-directory: javascript
      - run: npm run eslint-fix
        working-directory: javascript
      - run: ./scripts/fail-if-dirty
